export default [
    `Not going to lie, that is the sexiest chinchilla I have ever seen`,
    `You're such a fucking liar, Elmo`,
    `This milkshake really does bring all the boys to the yard`,
    `Please address me by my new stage name; DJ pickle skins`,
    `Always the bridesmaid, never the weirdly hot lunch lady`,
    `Stop right there! There's a mosquito on your change pocket`,
    `Don't you ever grab my wiffle balls`,
    `The princess WILL NOT be eating the fruit cake`,
    `Never underestimate the power of backup socks`,
    `Iron your sheets or pay the price!`,
    `I'll never forgive you for taking my stride `,
    `Knickerbockers can be shared, alas`,
    `Forget about the peanut butter, let's get nutty`,
    `Once I found a real life conversation`,
    `You can find your best self in the reflection of a butter knife`,
    `I'm not here to force my reckoning on you`,
    `Square tiles are actually just more square tiles`,
    `A wise man once said "don't forget your savory snack"`,
    `I will not meet your mother today, hamster!`,
    `She may be hot, but I prefer my spritzer cold`,
    `Are you old or did you just forget your stretches?`,
    `You can always count on me to not be counted on`,
    `If a bee has the power to sting you, can we not grant it access to wing you?`,
    `Falling asleep can be crazy but most the time it just happens`,
    `I will not clean your tiny home, Elon!`,
    `Stop that Jeanine, no one does that anymore`,
    `If you pet this dino I'll give you a cracker`,
    `A great great great great great big willy`,
    `triple dimple pickle pimple`,
    `Fight now or forever hold your fleece`,
    `Forget I told you about that nickel on the floor`,
    `Why can't you be more like my exwife?`,
    `The sun came at me today, it has zero chill`,
    `Once best known for rapping, now best at napping`,
]
