export default [
    `Not going to lie, that is the sexiest chinchilla I have ever seen`,
    `You're such a fucking liar, Elmo`,
    `This milkshake really does bring all the boys to the yard`,
    `Please address me by my new stage name; DJ pickle skins`,
    `Always the bridesmaid, never the weirdly hot lunch lady`,
    `Stop right there! There's a mosquito on your change pocket`,
    `Don't you ever grab my wiffle balls`,
    `The princess WILL NOT be eating the fruitcake`,
    `Never underestimate the power of backup socks`,
    `Iron your sheets or pay the price!`,
    `I'll never forgive you for taking my stride `,
    `Knickerbockers can be shared, alas`,
    `Forget about the peanut butter, let's get nutty`,
    `Once I found a real life conversation`,
    `You can find your best self in the reflection of a butter knife`,
    `I'm not here to force my reckoning on you`,
    `Square tiles are actually just more square tiles`,
    `A wise man once said "don't forget your savory snack"`,
    `I will not meet your mother today, hamster!`,
    `She may be hot, but I prefer my spritzer cold`,
    `Are you old or did you just forget your stretches?`,
    `You can always count on me to not be counted on`,
    `If a bee has the power to sting you, can we not grant it access to wing you?`,
    `Falling asleep can be crazy but most the time it just happens`,
    `I will not clean your tiny home, Elon!`,
    `Stop that Jeanine, no one does that anymore`,
    `If you pet this dino I'll give you a cracker`,
    `A great great great great great big willy`,
    `triple dimple pickle pimple`,
    `Fight now or forever hold your fleece`,
    `Forget I told you about that nickel on the floor`,
    `Why can't you be more like my exwife?`,
    `The sun came at me today, it has zero chill`,
    `Once best known for rapping, now best at napping`,
    `Stop what you're saying, there's spaghetti sauce on your face`,
    `If you think I'm hot you should see my collection of newts`,
    `Dammit Jenny, pick up your britches and bring me an apple `,
    `In facebook Groups waiting for other Toenail Munchers to login `,
    `How is it I'm the only one that burns my shavings?`,
    `Once when playing hockey I got royally pucked`,
    `A museum, but for all the hairs I've now lost`,
    `Picking up hotties at the Roger Stone rally`,
    `all urine aside, it was a pretty decent Christmas party`,
    `Except for Guam, tropical vacations seem quite fun!`,
    `Can't tell you enough how much I dislike your face`,
    `Stop trying to make me feel better with your clumpy pudding`,
    `If this button keeps popping I'll have to invest in a lifestyle`,
    `Hold it right there Rhonda, I'm not unpacking that mess`,
    `Christmas is coming, better get loaded`,
    `Fast track 7 years, I finally got the damn fungi`,
    `Forget drumming, give me those sweet sounds of the fiddle`,
    `Black licorice but as mouth bullets`,
    `Last time I ate a lizard for fun I ended up on CNN`,
    `Why wait for summer when you can swim in your sorrows all winter`,
    `My boyfriend is so unique, he eats rice by tongue flicking`,
    `Not long ago a wizzard told me I'd remain this flippant`,
    `Oh yeah this shirt was half off, bring me the seamstress!`,
    `White pants are ballsy for everyone involved`,
    `A detective once told me, never back away from a 12am Hershey's`,
    `I can't go I'm sorry, I don't like you much`,
    `Pillow fights are great until someone forgets their pillow`,
    `My parents met playing Words With Friends`,
    `Yeah Beyonce is cool, but have you ever rolled a Yahtzee? `,
    `Therapy is helpful but coffee is cheaper`,
    `Superbowl Plinko will not be happening again this year`,
    `Complaining will get you nowhere except everyone's head`,
    `Fancy tea drinkers think they don't need to pay the toll`,
    `Yeah my car makes noise, so does your bothersome mouth`,
    `Work one let me know it's not preferred I act human`,
    `I'm never not thinking about that time I met by boss on Hinge`,
    `Sit back and roll big fat Scoobie Doobie`,
]
